version: '2.1'

services:
  # Database instance
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=game"

  # Auth instance
  auth:
    image: eu.gcr.io/withergate-215313/withergate-auth
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  # Api instance
  api:
    image: eu.gcr.io/withergate-215313/withergate-api
    ports:
      - "8080:8080"
    restart: always
    environment:
      - "security.oauth2.resource.userInfoUri=http://auth:9000/user"
      - "spring.datasource.url=jdbc:mysql://database:3306/game?useSSL=false"
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - database
